<?php

declare(strict_types=1);

namespace Padosoft\LaravelFlowAdmin;

use Illuminate\Cookie\Middleware\EncryptCookies;
use Illuminate\Support\Facades\Blade;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\ServiceProvider;
use Padosoft\LaravelFlow\Contracts\DefinitionRepository;
use Padosoft\LaravelFlow\Dashboard\FlowDashboardReadModel;
use Padosoft\LaravelFlowAdmin\Adapters\ArrayReadModel;
use Padosoft\LaravelFlowAdmin\Adapters\EloquentReadModel;
use Padosoft\LaravelFlowAdmin\Authorizers\DenyAllAuthorizer;
use Padosoft\LaravelFlowAdmin\Contracts\ActionAuthorizer;
use Padosoft\LaravelFlowAdmin\Contracts\ReadModel;
use Padosoft\LaravelFlowAdmin\Http\Controllers\Assets\AdminCssController;
use Padosoft\LaravelFlowAdmin\Http\Controllers\Assets\StudioCssController;
use Padosoft\LaravelFlowAdmin\Http\Controllers\Assets\StudioJsController;
use Padosoft\LaravelFlowAdmin\Http\Controllers\ThemeController;

class FlowAdminServiceProvider extends ServiceProvider
{
    public function register(): void
    {
        $this->mergeConfigFrom(
            __DIR__ . '/../config/flow-admin.php',
            'flow-admin'
        );

        $this->app->singleton(FlowDashboardReadModel::class, function (): FlowDashboardReadModel {
            return new FlowDashboardReadModel;
        });

        $this->app->singleton(EloquentReadModel::class, function ($app): EloquentReadModel {
            return new EloquentReadModel(
                $app->make(FlowDashboardReadModel::class),
                $app->make(DefinitionRepository::class),
            );
        });

        $this->app->singleton(ReadModel::class, function ($app): ReadModel {
            $adapter = (string) $app->make('config')->get('flow-admin.adapter', 'eloquent');
            $arrayAdapter = ArrayReadModel::class;

            if (strtolower($adapter) === 'array' && class_exists($arrayAdapter)) {
                return $app->make($arrayAdapter);
            }

            return $app->make(EloquentReadModel::class);
        });

        $this->app->singleton(ActionAuthorizer::class, function ($app): ActionAuthorizer {
            $authorizerClass = $app->make('config')->get(
                'flow-admin.authorizer',
                DenyAllAuthorizer::class,
            );

            if (! is_string($authorizerClass) || ! class_exists($authorizerClass)) {
                return new DenyAllAuthorizer;
            }

            /** @var class-string<ActionAuthorizer> $authorizerClass */
            $authorizer = $app->make($authorizerClass);
            if (! $authorizer instanceof ActionAuthorizer) {
                return new DenyAllAuthorizer;
            }

            return $authorizer;
        });
    }

    public function boot(): void
    {
        $this->loadViewsFrom(__DIR__ . '/../resources/views', 'flow-admin');

        // Register file-based (anonymous) Blade components under the
        // `flow-admin` prefix. Templates use `<x-flow-admin::icon name="…" />`
        // resolved from `resources/views/components/icon.blade.php`. The
        // path-based registration (vs the class-based `componentNamespace`)
        // keeps the design-system primitives template-only — no PHP class
        // boilerplate per icon/badge/button.
        Blade::anonymousComponentPath(
            path: __DIR__ . '/../resources/views/components',
            prefix: 'flow-admin',
        );

        $this->loadRoutesFrom(__DIR__ . '/../routes/flow-admin.php');

        $this->registerPackagedAssetRoutes();

        // Exempt the theme-preference cookie from EncryptCookies. The
        // value is `light` or `dark` (publicly knowable), and Macro 8
        // wires up a JS theme-mirror in the ⌘K palette that reads
        // `document.cookie`; an encrypted payload would break both
        // assertions in tests and the runtime read. The cookie is also
        // explicitly `httpOnly: false` for the same reason.
        EncryptCookies::except(ThemeController::COOKIE_NAME);

        if ($this->app->runningInConsole()) {
            $this->publishes([
                __DIR__ . '/../config/flow-admin.php' => config_path('flow-admin.php'),
            ], 'flow-admin-config');

            $this->publishes([
                __DIR__ . '/../resources/views' => resource_path('views/vendor/flow-admin'),
            ], 'flow-admin-views');

            // flow-admin-assets tag publishes the *built* Vite bundle
            // (`.vite/manifest.json` + hashed `assets/*.{js,css}`), not the
            // pre-build source under `resources/`. Publishing source would
            // skip Vite, drop the manifest, and force consumers to re-bundle.
            //
            // The directory is generated by `npm run build` and is git-ignored
            // during development; release tarballs (Macro 9) include it via a
            // CI build-and-bundle step before `composer archive`. The guard
            // keeps `php artisan vendor:publish` honest before that point: if
            // the built tree is absent, the tag is simply not registered
            // instead of mapping a non-existent source.
            $builtAssetsPath = __DIR__ . '/../public/vendor/flow-admin';
            if (is_dir($builtAssetsPath)) {
                $this->publishes([
                    $builtAssetsPath => public_path('vendor/flow-admin'),
                ], 'flow-admin-assets');
            }
        }
    }

    /**
     * Register a static asset route that serves the package's design-system
     * stylesheet directly from `resources/css/admin.css`. The file is the
     * pixel-perfect port of `.design-source/project/styles.css` and provides
     * the design tokens (light + dark theme) consumed by every admin Blade
     * template.
     *
     * The handler is an invokable controller (`AdminCssController`), NOT a
     * closure: Laravel cannot serialise closures for `php artisan
     * route:cache`, which is a common production optimisation in consumer
     * apps. The controller form keeps the package route-cacheable and lets
     * the cache headers (Last-Modified, must-revalidate, max-age=300)
     * live in tested code rather than in this provider.
     *
     * Why a Laravel route instead of a Vite-built link tag:
     * - Testbench's `serve` command does not expose this package's
     *   `public/vendor/flow-admin/` build output through its public dir, so
     *   the Vite hashed-asset URL is unreachable during E2E.
     * - Consumer apps that have run `php artisan vendor:publish
     *   --tag=flow-admin-assets` get the optimised hashed assets via the
     *   normal Vite manifest at runtime; this fallback route is the
     *   "always works" path that does not require a publish step.
     * - The route is intentionally registered outside `routes/flow-admin.php`
     *   so it does NOT inherit the admin middleware stack (`web,auth`):
     *   stylesheets must be reachable for unauthenticated users too,
     *   otherwise the login redirect would render unstyled.
     *
     * The route lives under `/_flow-admin/assets/{file}` — the underscore
     * prefix marks it as a package-internal route, away from the
     * user-facing `/flow` namespace.
     */
    private function registerPackagedAssetRoutes(): void
    {
        Route::get('/_flow-admin/assets/admin.css', AdminCssController::class)
            ->name('flow-admin.assets.css');

        Route::get('/_flow-admin/assets/studio.js', StudioJsController::class)
            ->name('flow-admin.assets.studio-js');

        Route::get('/_flow-admin/assets/studio.css', StudioCssController::class)
            ->name('flow-admin.assets.studio-css');
    }
}
