<?php

declare(strict_types=1);

namespace Padosoft\LaravelFlowAdmin;

use Illuminate\Support\Facades\Route;
use Illuminate\Support\ServiceProvider;
use Symfony\Component\HttpFoundation\BinaryFileResponse;

class FlowAdminServiceProvider extends ServiceProvider
{
    public function register(): void
    {
        $this->mergeConfigFrom(
            __DIR__ . '/../config/flow-admin.php',
            'flow-admin'
        );
    }

    public function boot(): void
    {
        $this->loadViewsFrom(__DIR__ . '/../resources/views', 'flow-admin');

        $this->loadRoutesFrom(__DIR__ . '/../routes/flow-admin.php');

        $this->registerPackagedAssetRoutes();

        if ($this->app->runningInConsole()) {
            $this->publishes([
                __DIR__ . '/../config/flow-admin.php' => config_path('flow-admin.php'),
            ], 'flow-admin-config');

            $this->publishes([
                __DIR__ . '/../resources/views' => resource_path('views/vendor/flow-admin'),
            ], 'flow-admin-views');

            // flow-admin-assets tag publishes the *built* Vite bundle
            // (`.vite/manifest.json` + hashed `assets/*.{js,css}`), not the
            // pre-build source under `resources/`. Publishing source would
            // skip Vite, drop the manifest, and force consumers to re-bundle.
            //
            // The directory is generated by `npm run build` and is git-ignored
            // during development; release tarballs (Macro 9) include it via a
            // CI build-and-bundle step before `composer archive`. The guard
            // keeps `php artisan vendor:publish` honest before that point: if
            // the built tree is absent, the tag is simply not registered
            // instead of mapping a non-existent source.
            $builtAssetsPath = __DIR__ . '/../public/vendor/flow-admin';
            if (is_dir($builtAssetsPath)) {
                $this->publishes([
                    $builtAssetsPath => public_path('vendor/flow-admin'),
                ], 'flow-admin-assets');
            }
        }
    }

    /**
     * Register a static asset route that serves the package's design-system
     * stylesheet directly from `resources/css/admin.css`. The file is the
     * pixel-perfect port of `.design-source/project/styles.css` and provides
     * the design tokens (light + dark theme) consumed by every admin Blade
     * template.
     *
     * Why a Laravel route instead of a Vite-built link tag:
     * - Testbench's `serve` command does not expose this package's
     *   `public/vendor/flow-admin/` build output through its public dir, so
     *   the Vite hashed-asset URL is unreachable during E2E.
     * - Consumer apps that have run `php artisan vendor:publish
     *   --tag=flow-admin-assets` get the optimised hashed assets via the
     *   normal Vite manifest at runtime; this fallback route is the
     *   "always works" path that does not require a publish step.
     * - The route is intentionally registered outside `routes/flow-admin.php`
     *   so it does NOT inherit the admin middleware stack (`web,auth`):
     *   stylesheets must be reachable for unauthenticated users too,
     *   otherwise the login redirect would render unstyled.
     *
     * The bypass-headers route lives under `/_flow-admin/assets/{file}` —
     * the underscore prefix marks it as a package-internal route, away
     * from the user-facing `/flow` namespace.
     */
    private function registerPackagedAssetRoutes(): void
    {
        Route::get('/_flow-admin/assets/admin.css', function (): BinaryFileResponse {
            $path = __DIR__ . '/../resources/css/admin.css';

            return response()->file($path, [
                'Content-Type' => 'text/css; charset=utf-8',
                'Cache-Control' => 'public, max-age=86400',
            ]);
        })->name('flow-admin.assets.css');
    }
}
